//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.WebFace.Invoice.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.WebFace.Invoice.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Mov. Contable.
        /// </summary>
        public static string ACCOUNTANT_MOV_ID {
            get {
                return ResourceManager.GetString("ACCOUNTANT_MOV_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizar.
        /// </summary>
        public static string ACTION_AUTHENTICATION {
            get {
                return ResourceManager.GetString("ACTION_AUTHENTICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobrar.
        /// </summary>
        public static string ACTION_CHARGE {
            get {
                return ResourceManager.GetString("ACTION_CHARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Albarán.
        /// </summary>
        public static string ACTION_CLOSE_DELIVERY {
            get {
                return ResourceManager.GetString("ACTION_CLOSE_DELIVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Línea.
        /// </summary>
        public static string ACTION_CREATE_LINE {
            get {
                return ResourceManager.GetString("ACTION_CREATE_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberar.
        /// </summary>
        public static string ACTION_RELEASE {
            get {
                return ResourceManager.GetString("ACTION_RELEASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string ADDRESS {
            get {
                return ResourceManager.GetString("ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string AMOUNT {
            get {
                return ResourceManager.GetString("AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth Code.
        /// </summary>
        public static string AUTHCODE {
            get {
                return ResourceManager.GetString("AUTHCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta Bancaria.
        /// </summary>
        public static string BANK_ACCOUNT {
            get {
                return ResourceManager.GetString("BANK_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gastos bancarios.
        /// </summary>
        public static string BANK_CHARGES {
            get {
                return ResourceManager.GetString("BANK_CHARGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Nacimiento.
        /// </summary>
        public static string BIRTH_DATE {
            get {
                return ResourceManager.GetString("BIRTH_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe.
        /// </summary>
        public static string CHARGE_AMOUNT {
            get {
                return ResourceManager.GetString("CHARGE_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos.
        /// </summary>
        public static string CHARGE_DATA {
            get {
                return ResourceManager.GetString("CHARGE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar cobro.
        /// </summary>
        public static string CHARGE_EDIT {
            get {
                return ResourceManager.GetString("CHARGE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Cobro.
        /// </summary>
        public static string CHARGE_ID {
            get {
                return ResourceManager.GetString("CHARGE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobros.
        /// </summary>
        public static string CHARGE_LIST {
            get {
                return ResourceManager.GetString("CHARGE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado del cobro.
        /// </summary>
        public static string CHARGE_STATUS {
            get {
                return ResourceManager.GetString("CHARGE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Cobro.
        /// </summary>
        public static string CHARGE_TYPE {
            get {
                return ResourceManager.GetString("CHARGE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string CITY {
            get {
                return ResourceManager.GetString("CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string CLIENT {
            get {
                return ResourceManager.GetString("CLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de Cliente.
        /// </summary>
        public static string CLIENT_DETAIL {
            get {
                return ResourceManager.GetString("CLIENT_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Cliente.
        /// </summary>
        public static string CLIENT_EDIT {
            get {
                return ResourceManager.GetString("CLIENT_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string CLIENT_LIST {
            get {
                return ResourceManager.GetString("CLIENT_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Cliente.
        /// </summary>
        public static string CLIENT_NEW {
            get {
                return ResourceManager.GetString("CLIENT_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CODIGO {
            get {
                return ResourceManager.GetString("CODIGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto cliente.
        /// </summary>
        public static string CODIGO_PRODUCTO_CLIENTE {
            get {
                return ResourceManager.GetString("CODIGO_PRODUCTO_CLIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obs.
        /// </summary>
        public static string COMMENTS {
            get {
                return ResourceManager.GetString("COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepto.
        /// </summary>
        public static string CONCEPT {
            get {
                return ResourceManager.GetString("CONCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string COUNTRY {
            get {
                return ResourceManager.GetString("COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string CREATED {
            get {
                return ResourceManager.GetString("CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda.
        /// </summary>
        public static string CURRENCY {
            get {
                return ResourceManager.GetString("CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string DATE {
            get {
                return ResourceManager.GetString("DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albarán.
        /// </summary>
        public static string DELIVERY {
            get {
                return ResourceManager.GetString("DELIVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Líneas de Albarán.
        /// </summary>
        public static string DELIVERY_LINES_LIST {
            get {
                return ResourceManager.GetString("DELIVERY_LINES_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dto..
        /// </summary>
        public static string DISCOUNT {
            get {
                return ResourceManager.GetString("DISCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Dto..
        /// </summary>
        public static string DISCOUNT_PERCENT {
            get {
                return ResourceManager.GetString("DISCOUNT_PERCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carné de Conducir.
        /// </summary>
        public static string DRIVING_LICENSE {
            get {
                return ResourceManager.GetString("DRIVING_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previsión.
        /// </summary>
        public static string DUE_DATE {
            get {
                return ResourceManager.GetString("DUE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente.
        /// </summary>
        public static string DUE_OF_PAYMENT {
            get {
                return ResourceManager.GetString("DUE_OF_PAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expediente.
        /// </summary>
        public static string EXPEDIENT {
            get {
                return ResourceManager.GetString("EXPEDIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Expediente.
        /// </summary>
        public static string EXPEDIENT_ID {
            get {
                return ResourceManager.GetString("EXPEDIENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gastos.
        /// </summary>
        public static string EXPENSES {
            get {
                return ResourceManager.GetString("EXPENSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vencimiento.
        /// </summary>
        public static string EXPIRATION_DATE {
            get {
                return ResourceManager.GetString("EXPIRATION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasarela.
        /// </summary>
        public static string GATEWAY {
            get {
                return ResourceManager.GetString("GATEWAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string GROSS {
            get {
                return ResourceManager.GetString("GROSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agrupado.
        /// </summary>
        public static string GROUPPED {
            get {
                return ResourceManager.GetString("GROUPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factura.
        /// </summary>
        public static string INVOICE {
            get {
                return ResourceManager.GetString("INVOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Líneas de factura.
        /// </summary>
        public static string INVOICE_LINE_LIST {
            get {
                return ResourceManager.GetString("INVOICE_LINE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas.
        /// </summary>
        public static string INVOICE_LIST {
            get {
                return ResourceManager.GetString("INVOICE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fac. Bulto.
        /// </summary>
        public static string IS_PACK {
            get {
                return ResourceManager.GetString("IS_PACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kg.
        /// </summary>
        public static string KG_AMOUNT {
            get {
                return ResourceManager.GetString("KG_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipio.
        /// </summary>
        public static string MUNICIPALITY {
            get {
                return ResourceManager.GetString("MUNICIPALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota.
        /// </summary>
        public static string NOTE {
            get {
                return ResourceManager.GetString("NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        public static string OBSERVATIONS {
            get {
                return ResourceManager.GetString("OBSERVATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagado.
        /// </summary>
        public static string PAID_AMOUNT {
            get {
                return ResourceManager.GetString("PAID_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan Mask.
        /// </summary>
        public static string PANMASK {
            get {
                return ResourceManager.GetString("PANMASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasaporte.
        /// </summary>
        public static string PASSPORT {
            get {
                return ResourceManager.GetString("PASSPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Días Pago.
        /// </summary>
        public static string PAY_DAYS {
            get {
                return ResourceManager.GetString("PAY_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptado.
        /// </summary>
        public static string PAYMENT_ACCEPTED {
            get {
                return ResourceManager.GetString("PAYMENT_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de autenticación.
        /// </summary>
        public static string PAYMENT_AUTH_ERROR {
            get {
                return ResourceManager.GetString("PAYMENT_AUTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transacción denegada.
        /// </summary>
        public static string PAYMENT_DENIED {
            get {
                return ResourceManager.GetString("PAYMENT_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarjeta de crédito caducada.
        /// </summary>
        public static string PAYMENT_EXPIRED_CARD {
            get {
                return ResourceManager.GetString("PAYMENT_EXPIRED_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL de API.
        /// </summary>
        public static string PAYMENT_GATEWAY_API_HOST {
            get {
                return ResourceManager.GetString("PAYMENT_GATEWAY_API_HOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de Pasarela.
        /// </summary>
        public static string PAYMENT_GATEWAY_CODE {
            get {
                return ResourceManager.GetString("PAYMENT_GATEWAY_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta Curl CA.
        /// </summary>
        public static string PAYMENT_GATEWAY_CURL_CA {
            get {
                return ResourceManager.GetString("PAYMENT_GATEWAY_CURL_CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda.
        /// </summary>
        public static string PAYMENT_GATEWAY_CURRENCY {
            get {
                return ResourceManager.GetString("PAYMENT_GATEWAY_CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasarela de Pago.
        /// </summary>
        public static string PAYMENT_GATEWAY_GROUP_TITLE {
            get {
                return ResourceManager.GetString("PAYMENT_GATEWAY_GROUP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Comercio.
        /// </summary>
        public static string PAYMENT_GATEWAY_MERCHANT_CODE {
            get {
                return ResourceManager.GetString("PAYMENT_GATEWAY_MERCHANT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Comercio.
        /// </summary>
        public static string PAYMENT_GATEWAY_MERCHANT_NAME {
            get {
                return ResourceManager.GetString("PAYMENT_GATEWAY_MERCHANT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Pasarela.
        /// </summary>
        public static string PAYMENT_GATEWAY_NAME {
            get {
                return ResourceManager.GetString("PAYMENT_GATEWAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL de Operaciones.
        /// </summary>
        public static string PAYMENT_GATEWAY_OPERATION_HOST {
            get {
                return ResourceManager.GetString("PAYMENT_GATEWAY_OPERATION_HOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Signature.
        /// </summary>
        public static string PAYMENT_GATEWAY_SIGNATURE_KEY {
            get {
                return ResourceManager.GetString("PAYMENT_GATEWAY_SIGNATURE_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha podido contactar con su banco.
        /// </summary>
        public static string PAYMENT_INACCESIBLE_BANK {
            get {
                return ResourceManager.GetString("PAYMENT_INACCESIBLE_BANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarjeta de crédito no válida.
        /// </summary>
        public static string PAYMENT_INVALID_CARD {
            get {
                return ResourceManager.GetString("PAYMENT_INVALID_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Método de Pago.
        /// </summary>
        public static string PAYMENT_METHOD {
            get {
                return ResourceManager.GetString("PAYMENT_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error del sistema. Por favor, inténtelo pasados unos minutos.
        /// </summary>
        public static string PAYMENT_SYSTEM_ERROR {
            get {
                return ResourceManager.GetString("PAYMENT_SYSTEM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transacción {0} no encontrada.
        /// </summary>
        public static string PAYMENT_TRANSACTION_NOT_FOUND {
            get {
                return ResourceManager.GetString("PAYMENT_TRANSACTION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error desconocido.
        /// </summary>
        public static string PAYMENT_UNKOWN_ERROR {
            get {
                return ResourceManager.GetString("PAYMENT_UNKOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transacción cancelada por el usuario.
        /// </summary>
        public static string PAYMENT_USER_CANCELED {
            get {
                return ResourceManager.GetString("PAYMENT_USER_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medio de Pago.
        /// </summary>
        public static string PAYMENT_WAY {
            get {
                return ResourceManager.GetString("PAYMENT_WAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Móvil.
        /// </summary>
        public static string PHONE_NUMBER {
            get {
                return ResourceManager.GetString("PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        public static string PHOTO {
            get {
                return ResourceManager.GetString("PHOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string PRICE {
            get {
                return ResourceManager.GetString("PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        public static string PROVINCE {
            get {
                return ResourceManager.GetString("PROVINCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectificativa.
        /// </summary>
        public static string RECTIFICATION_INVOICE {
            get {
                return ResourceManager.GetString("RECTIFICATION_INVOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string RESOLVED {
            get {
                return ResourceManager.GetString("RESOLVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuesta.
        /// </summary>
        public static string RESPONSE {
            get {
                return ResourceManager.GetString("RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string SERIAL {
            get {
                return ResourceManager.GetString("SERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie.
        /// </summary>
        public static string SERIE {
            get {
                return ResourceManager.GetString("SERIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Imp..
        /// </summary>
        public static string TAX_BASE {
            get {
                return ResourceManager.GetString("TAX_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imp..
        /// </summary>
        public static string TAXES {
            get {
                return ResourceManager.GetString("TAXES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Imp..
        /// </summary>
        public static string TAXES_PERCENT {
            get {
                return ResourceManager.GetString("TAXES_PERCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depósito.
        /// </summary>
        public static string TITLE_DEPOSIT {
            get {
                return ResourceManager.GetString("TITLE_DEPOSIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factura.
        /// </summary>
        public static string TITLE_MAIN_DATA {
            get {
                return ResourceManager.GetString("TITLE_MAIN_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago.
        /// </summary>
        public static string TITLE_PAYMENT {
            get {
                return ResourceManager.GetString("TITLE_PAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TOTAL {
            get {
                return ResourceManager.GetString("TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transacción.
        /// </summary>
        public static string TRANSACTION {
            get {
                return ResourceManager.GetString("TRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Transacción.
        /// </summary>
        public static string TRANSACTION_ID {
            get {
                return ResourceManager.GetString("TRANSACTION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID EXT Transacción.
        /// </summary>
        public static string TRANSACTION_ID_EXT {
            get {
                return ResourceManager.GetString("TRANSACTION_ID_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transacciones.
        /// </summary>
        public static string TRANSACTION_LIST {
            get {
                return ResourceManager.GetString("TRANSACTION_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Transacción.
        /// </summary>
        public static string TRANSACTION_TYPE {
            get {
                return ResourceManager.GetString("TRANSACTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string USER {
            get {
                return ResourceManager.GetString("USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIF/CIF.
        /// </summary>
        public static string VAT_NUMBER {
            get {
                return ResourceManager.GetString("VAT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año.
        /// </summary>
        public static string YEAR {
            get {
                return ResourceManager.GetString("YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Postal.
        /// </summary>
        public static string ZIP_CODE {
            get {
                return ResourceManager.GetString("ZIP_CODE", resourceCulture);
            }
        }
    }
}
