//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.Face.Invoice.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.Face.Invoice.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string ACTIVO {
            get {
                return ResourceManager.GetString("ACTIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso.
        /// </summary>
        public static string ADVISE_TITLE {
            get {
                return ResourceManager.GetString("ADVISE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albaranes Facturados.
        /// </summary>
        public static string ALBARAN_FACTURADOS {
            get {
                return ResourceManager.GetString("ALBARAN_FACTURADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albaranes No Facturados.
        /// </summary>
        public static string ALBARAN_NO_FACTURADOS {
            get {
                return ResourceManager.GetString("ALBARAN_NO_FACTURADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los Albaranes.
        /// </summary>
        public static string ALBARAN_TODOS {
            get {
                return ResourceManager.GetString("ALBARAN_TODOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albaranes de Contado.
        /// </summary>
        public static string ALBARANES_CONTADO_TITLE {
            get {
                return ResourceManager.GetString("ALBARANES_CONTADO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string APLICAR_CAMBIOS {
            get {
                return ResourceManager.GetString("APLICAR_CAMBIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditar.
        /// </summary>
        public static string AUDITAR_TI {
            get {
                return ResourceManager.GetString("AUDITAR_TI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayudas.
        /// </summary>
        public static string AYUDAS {
            get {
                return ResourceManager.GetString("AYUDAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayudas Fomento Cobradas.
        /// </summary>
        public static string AYUDAS_FOMENTO_COBRADAS {
            get {
                return ResourceManager.GetString("AYUDAS_FOMENTO_COBRADAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayudas Transporte (Fomento).
        /// </summary>
        public static string AYUDAS_FOMENTO_PENDIENTES {
            get {
                return ResourceManager.GetString("AYUDAS_FOMENTO_PENDIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayudas POSEI (Ganado).
        /// </summary>
        public static string AYUDAS_POSEI_PENDIENTES {
            get {
                return ResourceManager.GetString("AYUDAS_POSEI_PENDIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayudas REA Cobradas.
        /// </summary>
        public static string AYUDAS_REA_COBRADAS {
            get {
                return ResourceManager.GetString("AYUDAS_REA_COBRADAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayudas REA (Alimentación).
        /// </summary>
        public static string AYUDAS_REA_PENDIENTES {
            get {
                return ResourceManager.GetString("AYUDAS_REA_PENDIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Cabeza de Ganado.
        /// </summary>
        public static string CABEZA_INPUT_TITLE {
            get {
                return ResourceManager.GetString("CABEZA_INPUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Caja.
        /// </summary>
        public static string CAJA_ADD_TITLE {
            get {
                return ResourceManager.GetString("CAJA_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de Caja.
        /// </summary>
        public static string CAJA_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("CAJA_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Caja .
        /// </summary>
        public static string CAJA_EDIT_TITLE {
            get {
                return ResourceManager.GetString("CAJA_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Caja.
        /// </summary>
        public static string CAJA_REPORT_TITLE {
            get {
                return ResourceManager.GetString("CAJA_REPORT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Cliente:.
        /// </summary>
        public static string CLIENTE_ADD_TITLE {
            get {
                return ResourceManager.GetString("CLIENTE_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de Cliente:.
        /// </summary>
        public static string CLIENTE_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("CLIENTE_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Cliente:.
        /// </summary>
        public static string CLIENTE_EDIT_TITLE {
            get {
                return ResourceManager.GetString("CLIENTE_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ficha del Cliente.
        /// </summary>
        public static string CLIENTE_TI {
            get {
                return ResourceManager.GetString("CLIENTE_TI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string CLIENTES {
            get {
                return ResourceManager.GetString("CLIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Cobro:.
        /// </summary>
        public static string COBRO_ADD_TITLE {
            get {
                return ResourceManager.GetString("COBRO_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobros: Cobros a Clientes.
        /// </summary>
        public static string COBRO_CLIENTES {
            get {
                return ResourceManager.GetString("COBRO_CLIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de Cobro:.
        /// </summary>
        public static string COBRO_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("COBRO_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Cobro:.
        /// </summary>
        public static string COBRO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("COBRO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Cobro:.
        /// </summary>
        public static string COBRO_LOCALIZE_TITLE {
            get {
                return ResourceManager.GetString("COBRO_LOCALIZE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Cobro REA.
        /// </summary>
        public static string COBRO_REA_ADD_TITLE {
            get {
                return ResourceManager.GetString("COBRO_REA_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Cobro REA:.
        /// </summary>
        public static string COBRO_REA_EDIT_TITLE {
            get {
                return ResourceManager.GetString("COBRO_REA_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobros: Lista Completa.
        /// </summary>
        public static string COBRO_TODOS {
            get {
                return ResourceManager.GetString("COBRO_TODOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Cobro de Factura:.
        /// </summary>
        public static string COBROFACTURA_NEW_TITLE {
            get {
                return ResourceManager.GetString("COBROFACTURA_NEW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Cobros de Fomento:.
        /// </summary>
        public static string COBROS_FOMENTO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("COBROS_FOMENTO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ficha de Cobros.
        /// </summary>
        public static string COBROS_TI {
            get {
                return ResourceManager.GetString("COBROS_TI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Concepto.
        /// </summary>
        public static string CONCEPTO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("CONCEPTO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Concepto.
        /// </summary>
        public static string CONCEPTO_NEW_TITLE {
            get {
                return ResourceManager.GetString("CONCEPTO_NEW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepto Libre:.
        /// </summary>
        public static string CONCEPTOLIBRE_TITLE {
            get {
                return ResourceManager.GetString("CONCEPTOLIBRE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar acción.
        /// </summary>
        public static string CONFIRM_TITLE {
            get {
                return ResourceManager.GetString("CONFIRM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Albarán de Salida.
        /// </summary>
        public static string CREAR_ALBARAN {
            get {
                return ResourceManager.GetString("CREAR_ALBARAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturar.
        /// </summary>
        public static string CREAR_FACTURA {
            get {
                return ResourceManager.GetString("CREAR_FACTURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de Efecto:.
        /// </summary>
        public static string EFFECT_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("EFFECT_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Efecto:.
        /// </summary>
        public static string EFFECT_EDIT_TITLE {
            get {
                return ResourceManager.GetString("EFFECT_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe vacio.
        /// </summary>
        public static string EMPTY_REPORT {
            get {
                return ResourceManager.GetString("EMPTY_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despachantes.
        /// </summary>
        public static string ESTIMADO_DESPACHANTE {
            get {
                return ResourceManager.GetString("ESTIMADO_DESPACHANTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navieras.
        /// </summary>
        public static string ESTIMADO_NAVIERA {
            get {
                return ResourceManager.GetString("ESTIMADO_NAVIERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedores.
        /// </summary>
        public static string ESTIMADO_PROVEEDOR {
            get {
                return ResourceManager.GetString("ESTIMADO_PROVEEDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trans. Destino.
        /// </summary>
        public static string ESTIMADO_TRANS_DESTINO {
            get {
                return ResourceManager.GetString("ESTIMADO_TRANS_DESTINO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trans. Origen.
        /// </summary>
        public static string ESTIMADO_TRANS_ORIGEN {
            get {
                return ResourceManager.GetString("ESTIMADO_TRANS_ORIGEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existencias.
        /// </summary>
        public static string EXISTENCIAS {
            get {
                return ResourceManager.GetString("EXISTENCIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar a Empresa.
        /// </summary>
        public static string EXPORT_TO_COMPANY {
            get {
                return ResourceManager.GetString("EXPORT_TO_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas Emitidas: Cobradas.
        /// </summary>
        public static string FACTURA_COBRADAS {
            get {
                return ResourceManager.GetString("FACTURA_COBRADAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas Emitidas: Pendientes.
        /// </summary>
        public static string FACTURA_PENDIENTES {
            get {
                return ResourceManager.GetString("FACTURA_PENDIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas Recibidas: Pagadas.
        /// </summary>
        public static string FACTURA_RECIBIDAS_PAGADAS {
            get {
                return ResourceManager.GetString("FACTURA_RECIBIDAS_PAGADAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas Recibidas: Pendientes.
        /// </summary>
        public static string FACTURA_RECIBIDAS_PENDIENTES {
            get {
                return ResourceManager.GetString("FACTURA_RECIBIDAS_PENDIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas Recibidas: Listado Completo.
        /// </summary>
        public static string FACTURA_RECIBIDAS_TODAS {
            get {
                return ResourceManager.GetString("FACTURA_RECIBIDAS_TODAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas Emitidas: Listado Completo.
        /// </summary>
        public static string FACTURA_TODAS {
            get {
                return ResourceManager.GetString("FACTURA_TODAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fras. Emitidas de Dudoso Cobro.
        /// </summary>
        public static string FACTURAS_EMITIDAS_DUDOSO_COBRO {
            get {
                return ResourceManager.GetString("FACTURAS_EMITIDAS_DUDOSO_COBRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas Emitidas Pendientes.
        /// </summary>
        public static string FACTURAS_EMITIDAS_PENDIENTES {
            get {
                return ResourceManager.GetString("FACTURAS_EMITIDAS_PENDIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas Estimadas Pendientes.
        /// </summary>
        public static string FACTURAS_ESTIMADAS {
            get {
                return ResourceManager.GetString("FACTURAS_ESTIMADAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas de Expedientes Ptes..
        /// </summary>
        public static string FACTURAS_EXPEDIENTES_PENDIENTES {
            get {
                return ResourceManager.GetString("FACTURAS_EXPEDIENTES_PENDIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas de Explotación Ptes..
        /// </summary>
        public static string FACTURAS_EXPLOTACION_PENDIENTES {
            get {
                return ResourceManager.GetString("FACTURAS_EXPLOTACION_PENDIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas Pendientes de Pago.
        /// </summary>
        public static string FACTURAS_PENDIENTES_PAGO {
            get {
                return ResourceManager.GetString("FACTURAS_PENDIENTES_PAGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Gasto:.
        /// </summary>
        public static string GASTO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("GASTO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Gasto.
        /// </summary>
        public static string GASTO_NEW_TITLE {
            get {
                return ResourceManager.GetString("GASTO_NEW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Gasto:.
        /// </summary>
        public static string GASTO_VIEW_TITLE {
            get {
                return ResourceManager.GetString("GASTO_VIEW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gastos Pendientes Estimados.
        /// </summary>
        public static string GASTOS_ESTIMADOS {
            get {
                return ResourceManager.GetString("GASTOS_ESTIMADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRPF.
        /// </summary>
        public static string GASTOS_IRPF {
            get {
                return ResourceManager.GetString("GASTOS_IRPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gastos Pendientes de Pago.
        /// </summary>
        public static string GASTOS_PENDIENTES {
            get {
                return ResourceManager.GetString("GASTOS_PENDIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguridad Social.
        /// </summary>
        public static string GASTOS_SEGURIDAD_SOCIAL {
            get {
                return ResourceManager.GetString("GASTOS_SEGURIDAD_SOCIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar Pagos.
        /// </summary>
        public static string GENERAR_PAGOS {
            get {
                return ResourceManager.GetString("GENERAR_PAGOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Gráfica.
        /// </summary>
        public static string GRAPH_TI {
            get {
                return ResourceManager.GetString("GRAPH_TI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar Pedido.
        /// </summary>
        public static string IMPORTAR_PEDIDO {
            get {
                return ResourceManager.GetString("IMPORTAR_PEDIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar Presupuesto.
        /// </summary>
        public static string IMPORTAR_PROFORMA {
            get {
                return ResourceManager.GetString("IMPORTAR_PROFORMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe asignado a la Factura.
        /// </summary>
        public static string IMPORTE_COBRO {
            get {
                return ResourceManager.GetString("IMPORTE_COBRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir Historia.
        /// </summary>
        public static string IMPRIMIR_HISTORIA {
            get {
                return ResourceManager.GetString("IMPRIMIR_HISTORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe: Cartera de Clientes.
        /// </summary>
        public static string INFORME_CARTERA_TITLE {
            get {
                return ResourceManager.GetString("INFORME_CARTERA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe: Inventario Valorado.
        /// </summary>
        public static string INFORME_INVENTARIO_VALORADO_TITLE {
            get {
                return ResourceManager.GetString("INFORME_INVENTARIO_VALORADO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe: Movimientos de Stock.
        /// </summary>
        public static string INFORME_MOVIMIENTOS_STOCK_TITLE {
            get {
                return ResourceManager.GetString("INFORME_MOVIMIENTOS_STOCK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe: Control de Pagos.
        /// </summary>
        public static string INFORME_PAGOS_TITLE {
            get {
                return ResourceManager.GetString("INFORME_PAGOS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRECIOS DE VENTA POR CLIENTES.
        /// </summary>
        public static string INFORME_PRECIOS_CLIENTES {
            get {
                return ResourceManager.GetString("INFORME_PRECIOS_CLIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRECIOS DE COMPRA POR PROVEEDORES.
        /// </summary>
        public static string INFORME_PRECIOS_PROVEEDORES {
            get {
                return ResourceManager.GetString("INFORME_PRECIOS_PROVEEDORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe: Listado de Precios.
        /// </summary>
        public static string INFORME_PRECIOS_TITLE {
            get {
                return ResourceManager.GetString("INFORME_PRECIOS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobros de Factura.
        /// </summary>
        public static string INVOICE_CHARGES_TI {
            get {
                return ResourceManager.GetString("INVOICE_CHARGES_TI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Productos.
        /// </summary>
        public static string LISTA_PRODUCTOS_TITLE {
            get {
                return ResourceManager.GetString("LISTA_PRODUCTOS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos asociados a un proveedor.
        /// </summary>
        public static string LISTAPRODPROV_TITLE {
            get {
                return ResourceManager.GetString("LISTAPRODPROV_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Préstamos.
        /// </summary>
        public static string LOANS {
            get {
                return ResourceManager.GetString("LOANS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOROSOS.
        /// </summary>
        public static string MOROSOS {
            get {
                return ResourceManager.GetString("MOROSOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimientos de bancos.
        /// </summary>
        public static string MOVS_BANCOS_LIST_REPORT_TITLE {
            get {
                return ResourceManager.GetString("MOVS_BANCOS_LIST_REPORT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear extractos pendientes.
        /// </summary>
        public static string NEW_EXTRACTO_TI {
            get {
                return ResourceManager.GetString("NEW_EXTRACTO_TI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nóminas.
        /// </summary>
        public static string NOMINAS {
            get {
                return ResourceManager.GetString("NOMINAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Ticket.
        /// </summary>
        public static string NUEVO_TICKET {
            get {
                return ResourceManager.GetString("NUEVO_TICKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir a Origen.
        /// </summary>
        public static string ORIGEN_TI {
            get {
                return ResourceManager.GetString("ORIGEN_TI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otros Gastos.
        /// </summary>
        public static string OTROS_GASTOS {
            get {
                return ResourceManager.GetString("OTROS_GASTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otros Gastos:.
        /// </summary>
        public static string OTROS_GASTOS_TITLE {
            get {
                return ResourceManager.GetString("OTROS_GASTOS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagos Estimados.
        /// </summary>
        public static string PAGOS_ESTIMADOS {
            get {
                return ResourceManager.GetString("PAGOS_ESTIMADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasivo.
        /// </summary>
        public static string PASIVO {
            get {
                return ResourceManager.GetString("PASIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente de Cobro.
        /// </summary>
        public static string PENDIENTE_COBRO {
            get {
                return ResourceManager.GetString("PENDIENTE_COBRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Precio.
        /// </summary>
        public static string PRECIO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("PRECIO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un Precio:.
        /// </summary>
        public static string PRECIO_INPUT_TITLE {
            get {
                return ResourceManager.GetString("PRECIO_INPUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Precio.
        /// </summary>
        public static string PRECIO_NEW_TITLE {
            get {
                return ResourceManager.GetString("PRECIO_NEW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comercio Exterior.
        /// </summary>
        public static string PRESTAMOS_COMERCIO_EXTERIOR {
            get {
                return ResourceManager.GetString("PRESTAMOS_COMERCIO_EXTERIOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir Ficha.
        /// </summary>
        public static string PRINT_COBROS_LIST {
            get {
                return ResourceManager.GetString("PRINT_COBROS_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir Detalle.
        /// </summary>
        public static string PRINT_DETAIL_TI {
            get {
                return ResourceManager.GetString("PRINT_DETAIL_TI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedores.
        /// </summary>
        public static string PROVEEDORES {
            get {
                return ResourceManager.GetString("PROVEEDORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESULTADO.
        /// </summary>
        public static string RESULTADO_BALANCE {
            get {
                return ResourceManager.GetString("RESULTADO_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIESGO.
        /// </summary>
        public static string RIESGO {
            get {
                return ResourceManager.GetString("RIESGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un Cliente:.
        /// </summary>
        public static string SELECT_CLIENT {
            get {
                return ResourceManager.GetString("SELECT_CLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobros disponibles de:.
        /// </summary>
        public static string SELECT_COBRO_TITLE {
            get {
                return ResourceManager.GetString("SELECT_COBRO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un despachante.
        /// </summary>
        public static string SELECT_DESPACHANTE {
            get {
                return ResourceManager.GetString("SELECT_DESPACHANTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una empresa.
        /// </summary>
        public static string SELECT_EMPRESA {
            get {
                return ResourceManager.GetString("SELECT_EMPRESA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una naviera.
        /// </summary>
        public static string SELECT_NAVIERA {
            get {
                return ResourceManager.GetString("SELECT_NAVIERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un proveedor.
        /// </summary>
        public static string SELECT_PROVEEDOR {
            get {
                return ResourceManager.GetString("SELECT_PROVEEDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un puerto.
        /// </summary>
        public static string SELECT_PUERTO {
            get {
                return ResourceManager.GetString("SELECT_PUERTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una serie.
        /// </summary>
        public static string SELECT_SERIE {
            get {
                return ResourceManager.GetString("SELECT_SERIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un transportista.
        /// </summary>
        public static string SELECT_TRANSPORTISTA {
            get {
                return ResourceManager.GetString("SELECT_TRANSPORTISTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar email.
        /// </summary>
        public static string SEND_EMAIL {
            get {
                return ResourceManager.GetString("SEND_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir Servicio.
        /// </summary>
        public static string SERVICIOPROVEEDOR_ADD_TITLE {
            get {
                return ResourceManager.GetString("SERVICIOPROVEEDOR_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles del Servicio.
        /// </summary>
        public static string SERVICIOPROVEEDOR_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("SERVICIOPROVEEDOR_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Servicio.
        /// </summary>
        public static string SERVICIOPROVEEDOR_EDIT_TITLE {
            get {
                return ResourceManager.GetString("SERVICIOPROVEEDOR_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tesorería.
        /// </summary>
        public static string TESORERIA {
            get {
                return ResourceManager.GetString("TESORERIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Últimas ventas del producto.
        /// </summary>
        public static string ULTIMAS_VENTAS_PRODUCTO {
            get {
                return ResourceManager.GetString("ULTIMAS_VENTAS_PRODUCTO", resourceCulture);
            }
        }
    }
}
