//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.Face.Invoice.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.Face.Invoice.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una factura de este tipo de acreedor asociada al expediente. ¿Desea establecer esta como la factura principal de este acreedor para el expediente seleccionado?.
        /// </summary>
        public static string ACREEDOR_EXISTENTE {
            get {
                return ResourceManager.GetString("ACREEDOR_EXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe un ticket asociado a este albarán.
        /// </summary>
        public static string ALBARAN_TICKET_EXISTS {
            get {
                return ResourceManager.GetString("ALBARAN_TICKET_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este alumno ya ha sido asociado al cliente.
        /// </summary>
        public static string ALUMNO_YA_ASOCIADO {
            get {
                return ResourceManager.GetString("ALUMNO_YA_ASOCIADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;ATENCION: Está usted vendiendo con beneficio inferior al beneficio mínimo establecido para el producto. ¿Desea continuar?&quot;.
        /// </summary>
        public static string AVISO_BENEFICIO_MINIMO {
            get {
                return ResourceManager.GetString("AVISO_BENEFICIO_MINIMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;ATENCION: Está usted vendiendo en pérdida o sin beneficio. ¿Desea continuar?&quot;.
        /// </summary>
        public static string AVISO_PERDIDA {
            get {
                return ResourceManager.GetString("AVISO_PERDIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;ATENCION: Está usted intentado añadir un producto cuyo stock quedará por debajo del mínimo que se ha indicado para el mismo. ¿Desea continuar?&quot;.
        /// </summary>
        public static string AVISO_STOCK_MINIMO {
            get {
                return ResourceManager.GetString("AVISO_STOCK_MINIMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bancos.
        /// </summary>
        public static string BANCOS {
            get {
                return ResourceManager.GetString("BANCOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bultos insuficientes. Cantidad actual:.
        /// </summary>
        public static string BULTOS_INSUFICIENTES {
            get {
                return ResourceManager.GetString("BULTOS_INSUFICIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caja.
        /// </summary>
        public static string CAJA {
            get {
                return ResourceManager.GetString("CAJA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imposible eliminar este cobro. Tiene asociada la línea de caja nº {0} de fecha {1} que está incluida en un cierre de caja..
        /// </summary>
        public static string CIERRE_CAJA_COBRO {
            get {
                return ResourceManager.GetString("CIERRE_CAJA_COBRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agrupando albaranes y actualizando stocks....
        /// </summary>
        public static string COMPACTANDO_ALBARANES {
            get {
                return ResourceManager.GetString("COMPACTANDO_ALBARANES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El crédito dispuesto ({0}) por este cliente es superior a su crédito disponible ({1}).
        ///¿Continuar con la operación?.
        /// </summary>
        public static string CREDITO_DISPUESTO {
            get {
                return ResourceManager.GetString("CREDITO_DISPUESTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible cambiar el expediente de un concepto con stock asociado. Para ello elimine la línea y vuelva a crearla..
        /// </summary>
        public static string DELIVERY_LINE_EXPEDIENT_WARNING {
            get {
                return ResourceManager.GetString("DELIVERY_LINE_EXPEDIENT_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efectos Negociados.
        /// </summary>
        public static string EFECTOS_NEGOCIADOS {
            get {
                return ResourceManager.GetString("EFECTOS_NEGOCIADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efectos Pendientes de Cobro.
        /// </summary>
        public static string EFECTOS_PENDIENTES {
            get {
                return ResourceManager.GetString("EFECTOS_PENDIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efectos Pendientes de Vencimiento.
        /// </summary>
        public static string EFECTOS_PENDIENTES_VTO {
            get {
                return ResourceManager.GetString("EFECTOS_PENDIENTES_VTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existencias.
        /// </summary>
        public static string EXISTENCIAS {
            get {
                return ResourceManager.GetString("EXISTENCIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportación finalizada con éxito.
        ///¿Desea ver el registro de exportación?.
        /// </summary>
        public static string EXPORTACION_SUCCESS {
            get {
                return ResourceManager.GetString("EXPORTACION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportando Ayudas.
        /// </summary>
        public static string EXPORTANDO_AYUDAS {
            get {
                return ResourceManager.GetString("EXPORTANDO_AYUDAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportando Cobros.
        /// </summary>
        public static string EXPORTANDO_COBROS {
            get {
                return ResourceManager.GetString("EXPORTANDO_COBROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportando Facturas Emitidas.
        /// </summary>
        public static string EXPORTANDO_FACTURAS_EMITIDAS {
            get {
                return ResourceManager.GetString("EXPORTANDO_FACTURAS_EMITIDAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportando Facturas Recibidas.
        /// </summary>
        public static string EXPORTANDO_FACTURAS_RECIBIDAS {
            get {
                return ResourceManager.GetString("EXPORTANDO_FACTURAS_RECIBIDAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportando Gastos.
        /// </summary>
        public static string EXPORTANDO_GASTOS {
            get {
                return ResourceManager.GetString("EXPORTANDO_GASTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportando Nóminas.
        /// </summary>
        public static string EXPORTANDO_NOMINAS {
            get {
                return ResourceManager.GetString("EXPORTANDO_NOMINAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportando Pagos.
        /// </summary>
        public static string EXPORTANDO_PAGOS {
            get {
                return ResourceManager.GetString("EXPORTANDO_PAGOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportando Préstamos.
        /// </summary>
        public static string EXPORTANDO_PRESTAMOS {
            get {
                return ResourceManager.GetString("EXPORTANDO_PRESTAMOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportando Traspasos.
        /// </summary>
        public static string EXPORTANDO_TRASPASOS {
            get {
                return ResourceManager.GetString("EXPORTANDO_TRASPASOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportando albaranes de salida....
        /// </summary>
        public static string EXPORTING_OUTPUT_DELIVERIES {
            get {
                return ResourceManager.GetString("EXPORTING_OUTPUT_DELIVERIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportando facturas emitidas....
        /// </summary>
        public static string EXPORTING_OUTPUT_INVOICES {
            get {
                return ResourceManager.GetString("EXPORTING_OUTPUT_INVOICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible cambiar el Cliente a una factura con albaranes asociados..
        /// </summary>
        public static string FACTURA_CON_ALBARANES {
            get {
                return ResourceManager.GetString("FACTURA_CON_ALBARANES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generando facturas....
        /// </summary>
        public static string GENERANDO_FACTURAS {
            get {
                return ResourceManager.GetString("GENERANDO_FACTURAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importando albaranes seleccionados....
        /// </summary>
        public static string IMPORTANDO_ALBARANES {
            get {
                return ResourceManager.GetString("IMPORTANDO_ALBARANES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El precio introducido no es correcto..
        /// </summary>
        public static string INCORRECT_PRICE {
            get {
                return ResourceManager.GetString("INCORRECT_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando Exportación.
        /// </summary>
        public static string INICIANDO_EXPORTACION {
            get {
                return ResourceManager.GetString("INICIANDO_EXPORTACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El precio introducido no es correcto. Debe ser mayor que 0..
        /// </summary>
        public static string INVALID_PRICE {
            get {
                return ResourceManager.GetString("INVALID_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha indicado el Centro de Trabajo.
        /// </summary>
        public static string NO_CENTRO_SELECTED {
            get {
                return ResourceManager.GetString("NO_CENTRO_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un cliente.
        /// </summary>
        public static string NO_CLIENT_SELECTED {
            get {
                return ResourceManager.GetString("NO_CLIENT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha indicado la Empresa.
        /// </summary>
        public static string NO_COMPANY_SELECTED {
            get {
                return ResourceManager.GetString("NO_COMPANY_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un cliente destino.
        /// </summary>
        public static string NO_DESTINY_CLIENT_SELECTED {
            get {
                return ResourceManager.GetString("NO_DESTINY_CLIENT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha seleccionado el titular de destino.
        /// </summary>
        public static string NO_HOLDER_SELECTED {
            get {
                return ResourceManager.GetString("NO_HOLDER_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha seleccionado el Medio de pago.
        /// </summary>
        public static string NO_MEDIO_PAGO_SELECTED {
            get {
                return ResourceManager.GetString("NO_MEDIO_PAGO_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un puerto.
        /// </summary>
        public static string NO_PORT_SELECTED {
            get {
                return ResourceManager.GetString("NO_PORT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha puesto ningun precio. Asocie un precio al producto antes de continuar..
        /// </summary>
        public static string NO_PRICE {
            get {
                return ResourceManager.GetString("NO_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un proveedor.
        /// </summary>
        public static string NO_PROV_SELECTED {
            get {
                return ResourceManager.GetString("NO_PROV_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una serie.
        /// </summary>
        public static string NO_SERIE_SELECTED {
            get {
                return ResourceManager.GetString("NO_SERIE_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un cliente origen.
        /// </summary>
        public static string NO_SOURCE_CLIENT_SELECTED {
            get {
                return ResourceManager.GetString("NO_SOURCE_CLIENT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un parte de trabajo.
        /// </summary>
        public static string NO_WORK_REPORT_SELECTED {
            get {
                return ResourceManager.GetString("NO_WORK_REPORT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COBROS PTES. CON VTO. ANTERIOR AL {0}.
        /// </summary>
        public static string NOFITY_COBROS_PENDIENTES {
            get {
                return ResourceManager.GetString("NOFITY_COBROS_PENDIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRAS. EMITIDAS PTES. CON PREV. ANTERIOR AL {0}.
        /// </summary>
        public static string NOFITY_FACTURAS_EMITIDAS_PENDIENTES {
            get {
                return ResourceManager.GetString("NOFITY_FACTURAS_EMITIDAS_PENDIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercancía que se acoge a los beneficios de la ayuda REA en cumplimiento del Reglamento 247/06 del Consejo..
        /// </summary>
        public static string NOTA_FACTURA {
            get {
                return ResourceManager.GetString("NOTA_FACTURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COBROS VENCIDOS A {0}.
        /// </summary>
        public static string NOTIFY_COBROS_VENCIDOS {
            get {
                return ResourceManager.GetString("NOTIFY_COBROS_VENCIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Préstamos Pendientes de Vencimiento.
        /// </summary>
        public static string PAGO_PRESTAMOS_PTES_VTO {
            get {
                return ResourceManager.GetString("PAGO_PRESTAMOS_PTES_VTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas Pendientes Estimadas.
        /// </summary>
        public static string PAGOS_ESTIMADOS {
            get {
                return ResourceManager.GetString("PAGOS_ESTIMADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido completo. No existen artículos pendientes de servir..
        /// </summary>
        public static string PEDIDO_COMPLETO {
            get {
                return ResourceManager.GetString("PEDIDO_COMPLETO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El préstamo que está intentando borrar está asociado a un pago de factura y no es posible realizar la operación..
        /// </summary>
        public static string PRESTAMO_ASOCIADO_PAGO_FACTURA {
            get {
                return ResourceManager.GetString("PRESTAMO_ASOCIADO_PAGO_FACTURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible borrar el préstamo seleccionado mientras tenga pagos asociados..
        /// </summary>
        public static string PRESTAMO_CON_PAGOS_ASOCIADOS {
            get {
                return ResourceManager.GetString("PRESTAMO_CON_PAGOS_ASOCIADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El préstamo actual ya contiene pagos. ¿Desea mantener estos pagos junto con los nuevos que se generarán? En caso contrario, se anularán los pagos que existen actualmente..
        /// </summary>
        public static string PRESTAMO_CON_PAGOS_PREVIOS {
            get {
                return ResourceManager.GetString("PRESTAMO_CON_PAGOS_PREVIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimiendo listado de {0}....
        /// </summary>
        public static string PRINTING {
            get {
                return ResourceManager.GetString("PRINTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obteniendo datos del Balance.
        /// </summary>
        public static string RETRIEVING_BALANCE {
            get {
                return ResourceManager.GetString("RETRIEVING_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obteniendo extractos de Tarjetas de Crédito.
        /// </summary>
        public static string RETRIEVING_EXTRACTOS {
            get {
                return ResourceManager.GetString("RETRIEVING_EXTRACTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock insuficiente. Cantidad actual:.
        /// </summary>
        public static string STOCK_INSUFICIENTE {
            get {
                return ResourceManager.GetString("STOCK_INSUFICIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock insuficiente del componente {0}.
        /// </summary>
        public static string STOCK_INSUFICIENTE_COMPONENTE {
            get {
                return ResourceManager.GetString("STOCK_INSUFICIENTE_COMPONENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los tipos de interés introducidos no son válidos. Tenga en cuenta que la fecha de inicio de cada periodo debe ser previa a la de finalización y que los periodos no se pueden solapar entre ellos..
        /// </summary>
        public static string TIPOS_INTERES_NO_VALIDOS {
            get {
                return ResourceManager.GetString("TIPOS_INTERES_NO_VALIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible asignar albaranes de titulares distintos a una misma Factura.
        /// </summary>
        public static string TITULAR_FACTURA_DIFERENTE {
            get {
                return ResourceManager.GetString("TITULAR_FACTURA_DIFERENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniendo Clientes.
        /// </summary>
        public static string UNIENDO_CLIENTES {
            get {
                return ResourceManager.GetString("UNIENDO_CLIENTES", resourceCulture);
            }
        }
    }
}
